# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: les/drivers/drivers.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from les.mp_model import mp_model_pb2 as les_dot_mp__model_dot_mp__model__pb2
from les.decomposers import decomposers_pb2 as les_dot_decomposers_dot_decomposers__pb2
from les.backend_solvers import backend_solvers_pb2 as les_dot_backend__solvers_dot_backend__solvers__pb2
from les.solution_tables import solution_tables_pb2 as les_dot_solution__tables_dot_solution__tables__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19les/drivers/drivers.proto\x12\x0bles.drivers\x1a\x1bles/mp_model/mp_model.proto\x1a!les/decomposers/decomposers.proto\x1a)les/backend_solvers/backend_solvers.proto\x1a)les/solution_tables/solution_tables.proto\"\xf1\x01\n\x10\x44riverParameters\x12=\n\x06\x64river\x18\x01 \x02(\x0e\x32\x13.les.drivers.Driver:\x18LOCAL_ELIMINATION_DRIVER\x12\x42\n\x16\x64\x65\x66\x61ult_backend_solver\x18\x02 \x01(\x0e\x32\".les.backend_solvers.BackendSolver\x12Z\n#local_elimination_driver_parameters\x18\x03 \x01(\x0b\x32-.les.drivers.LocalEliminationDriverParameters\"\xb7\x02\n LocalEliminationDriverParameters\x12$\n\x18max_num_shared_variables\x18\x01 \x01(\x03:\x02\x31\x30\x12R\n\ndecomposer\x18\x02 \x01(\x0e\x32\x1b.les.decomposers.Decomposer:!QUASIBLOCK_FINKELSTEIN_DECOMPOSER\x12Q\n\x0esolution_table\x18\x03 \x01(\x0e\x32\".les.solution_tables.SolutionTable:\x15SQLITE_SOLUTION_TABLE\x12\x46\n\x1arelaxation_backend_solvers\x18\x04 \x03(\x0e\x32\".les.backend_solvers.BackendSolver*&\n\x06\x44river\x12\x1c\n\x18LOCAL_ELIMINATION_DRIVER\x10\x00:^\n\x11\x64river_parameters\x12$.les.mp_model.OptimizationParameters\x18\x64 \x01(\x0b\x32\x1d.les.drivers.DriverParameters')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'les.drivers.drivers_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  les_dot_mp__model_dot_mp__model__pb2.OptimizationParameters.RegisterExtension(driver_parameters)

  DESCRIPTOR._options = None
  _DRIVER._serialized_start=750
  _DRIVER._serialized_end=788
  _DRIVERPARAMETERS._serialized_start=193
  _DRIVERPARAMETERS._serialized_end=434
  _LOCALELIMINATIONDRIVERPARAMETERS._serialized_start=437
  _LOCALELIMINATIONDRIVERPARAMETERS._serialized_end=748
# @@protoc_insertion_point(module_scope)
