# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: les/executors/executors.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from les.mp_model import mp_model_pb2 as les_dot_mp__model_dot_mp__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='les/executors/executors.proto',
  package='les.executors',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1dles/executors/executors.proto\x12\rles.executors\x1a\x1bles/mp_model/mp_model.proto\"O\n\x12\x45xecutorParameters\x12\x39\n\x08\x65xecutor\x18\x01 \x02(\x0e\x32\x17.les.executors.Executor:\x0e\x44UMMY_EXECUTOR*3\n\x08\x45xecutor\x12\x12\n\x0e\x44UMMY_EXECUTOR\x10\x00\x12\x13\n\x0fTHREAD_EXECUTOR\x10\x01:d\n\x13\x65xecutor_parameters\x12$.les.mp_model.OptimizationParameters\x18\x66 \x01(\x0b\x32!.les.executors.ExecutorParameters')
  ,
  dependencies=[les_dot_mp__model_dot_mp__model__pb2.DESCRIPTOR,])

_EXECUTOR = _descriptor.EnumDescriptor(
  name='Executor',
  full_name='les.executors.Executor',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='DUMMY_EXECUTOR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='THREAD_EXECUTOR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=158,
  serialized_end=209,
)
_sym_db.RegisterEnumDescriptor(_EXECUTOR)

Executor = enum_type_wrapper.EnumTypeWrapper(_EXECUTOR)
DUMMY_EXECUTOR = 0
THREAD_EXECUTOR = 1

EXECUTOR_PARAMETERS_FIELD_NUMBER = 102
executor_parameters = _descriptor.FieldDescriptor(
  name='executor_parameters', full_name='les.executors.executor_parameters', index=0,
  number=102, type=11, cpp_type=10, label=1,
  has_default_value=False, default_value=None,
  message_type=None, enum_type=None, containing_type=None,
  is_extension=True, extension_scope=None,
  serialized_options=None, file=DESCRIPTOR)


_EXECUTORPARAMETERS = _descriptor.Descriptor(
  name='ExecutorParameters',
  full_name='les.executors.ExecutorParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executor', full_name='les.executors.ExecutorParameters.executor', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=156,
)

_EXECUTORPARAMETERS.fields_by_name['executor'].enum_type = _EXECUTOR
DESCRIPTOR.message_types_by_name['ExecutorParameters'] = _EXECUTORPARAMETERS
DESCRIPTOR.enum_types_by_name['Executor'] = _EXECUTOR
DESCRIPTOR.extensions_by_name['executor_parameters'] = executor_parameters
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecutorParameters = _reflection.GeneratedProtocolMessageType('ExecutorParameters', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTORPARAMETERS,
  __module__ = 'les.executors.executors_pb2'
  # @@protoc_insertion_point(class_scope:les.executors.ExecutorParameters)
  ))
_sym_db.RegisterMessage(ExecutorParameters)

executor_parameters.message_type = _EXECUTORPARAMETERS
les_dot_mp__model_dot_mp__model__pb2.OptimizationParameters.RegisterExtension(executor_parameters)

# @@protoc_insertion_point(module_scope)
