# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: les/solution_tables/solution_tables.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from les.mp_model import mp_model_pb2 as les_dot_mp__model_dot_mp__model__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n)les/solution_tables/solution_tables.proto\x12\x13les.solution_tables\x1a\x1bles/mp_model/mp_model.proto**\n\rSolutionTable\x12\x19\n\x15SQLITE_SOLUTION_TABLE\x10\x00')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'les.solution_tables.solution_tables_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _SOLUTIONTABLE._serialized_start = 95
    _SOLUTIONTABLE._serialized_end = 137
# @@protoc_insertion_point(module_scope)
