# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: les/solution_tables/solution_tables.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from les.mp_model import mp_model_pb2 as les_dot_mp__model_dot_mp__model__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='les/solution_tables/solution_tables.proto',
  package='les.solution_tables',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n)les/solution_tables/solution_tables.proto\x12\x13les.solution_tables\x1a\x1bles/mp_model/mp_model.proto**\n\rSolutionTable\x12\x19\n\x15SQLITE_SOLUTION_TABLE\x10\x00')
  ,
  dependencies=[les_dot_mp__model_dot_mp__model__pb2.DESCRIPTOR,])

_SOLUTIONTABLE = _descriptor.EnumDescriptor(
  name='SolutionTable',
  full_name='les.solution_tables.SolutionTable',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SQLITE_SOLUTION_TABLE', index=0, number=0,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=95,
  serialized_end=137,
)
_sym_db.RegisterEnumDescriptor(_SOLUTIONTABLE)

SolutionTable = enum_type_wrapper.EnumTypeWrapper(_SOLUTIONTABLE)
SQLITE_SOLUTION_TABLE = 0


DESCRIPTOR.enum_types_by_name['SolutionTable'] = _SOLUTIONTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
